name: loker_express
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-4.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - lib/assets/banner-homepage.jpg
    - lib/assets/hire-me.png
    - lib/assets/teacher-hiring.png
    - lib/assets/earth-planet.png